# Para producción AWS
aws.accessKeyId=TU_ACCESS_KEY
aws.secretKey=TU_SECRET_KEY
aws.region=us-east-1

# Para RDS
spring.datasource.url=jdbc:postgresql://tu-rds-endpoint:5432/crud_db
spring.datasource.username=admin
spring.datasource.password=

# O para DynamoDB
aws.dynamodb.endpoint=
